### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [yauhenikh/slack-ui#1]
Hello @yauhenikh, 
The goal is to check and improve skill of creating markup based on design or mockup.
So let's try to make it better! 
 - the layout looks broken as soon as we have vertical scroll
![image](https://user-images.githubusercontent.com/5592397/87879303-804cb200-c9f2-11ea-9d63-e18172bdb8a7.png)

 - please add a few types of messages: link share, quoted text, video, audio, 
 - add tooltips for icons

Thank you for the efforts!

**Comment by yauhenikh** [comment]
Greetings, @IlyaMokin
Thank you for the review. 
I updated the page according to your comments.

**Comment by IlyaMokin** [comment]
Looks fine now. The ticket can be closed. We will be checking your JS tasks soon, thank you!
